import { Stepper } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Benji Book</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stepper active={0}>
        <Stepper.Step label="Step 1">
          The first step
        </Stepper.Step>
        <Stepper.Step label="Step 2">
          The second step
        </Stepper.Step>
        <Stepper.Step label="Step 3">
          The third step
        </Stepper.Step>
        <Stepper.Completed>
          Completed, click back button to get to previous step
        </Stepper.Completed>
      </Stepper>
    </>
  );
};

export default Home;