import { type NextPage } from "next";
import Head from "next/head";
import AboutYouForm from "../components/AboutYouForm/AboutYourForm";
import SignIn from "../components/SignIn/SignIn";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Benji Book</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutYouForm />
    </>
  );
};

export default Home;